---
- name: Create a VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ cidr_vnet }}"
    region: "{{ region }}"
    tags:
      Name: "{{ vpc_name }}"
    tenancy: default
  register: vpc

- name: Create an Internet Gateway
  #amazon.aws.ec2_igw:
  amazon.aws.ec2_vpc_igw:
    region: "{{ region }}"
    vpc_id: "{{ vpc.vpc.id }}"
    tags:
      Name: "{{ vpc_name }}-igw"
  register: igw

- name: Crear Subnets
  import_tasks: subnet.yml

- name: Crear Route Table
  import_tasks: route_table.yml

- name: Crear Security Group
  import_tasks: security_group.yml