---
- name: Create a VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ cidr_vnet }}"
    region: "{{ region }}"
    tags:
      Name: "{{ vpc_name }}"
    tenancy: default
  register: vpc

- name: Crear Subnets
  import_tasks: subnet.yml