---
- name: Create a VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ cidr_vnet }}"
    region: "{{ region }}"
    tags:
      Name: "{{ vpc_name }}"
    tenancy: default
  register: vpc

- name: Create an Internet Gateway
  amazon.aws.ec2_igw:
    region: "{{ region }}"
    vpc_id: "{{ vpc.vpc.id }}"
    tags:
      Name: "{{ vpc_name }}-igw"
  register: igw

- name: Attach Internet Gateway to VPC
  amazon.aws.ec2_vpc_igw:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    igw_id: "{{ igw.gateway.id }}"
    region: "{{ region }}"


- name: Crear Subnets
  import_tasks: subnet.yml