- name: Security group Public
  amazon.aws.ec2_security_group:
    name: "{{ sg_name }}"
    description: sg with rule descriptions
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        ports:
        - 80
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on port 80
    
    rules_egress:
      - proto: -1
        cidr_ip: 0.0.0.0/0
        # description to use if example-other needs to be created
        group_desc: allow all outbound traffic