# Gather information about any VPC with a tag key Name and value Example
# - amazon.aws.ec2_vpc_net_info:
#     filters:
#       "tag:Name": "{{ vpc_name }}"

- name: Create subnet 1 in VPC
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ cidr_subnet1 }}"
    az: "{{ az1 }}"
    map_public: yes
    region: "{{ region }}"
    tags:
      Name: "{{ vpc_name }}-subnet-1"