- name: Create Virtual Network
  azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      #name: "{{ name }}{{ rpfx }}"
      name: "{{ vnet_name }}"
      address_prefixes_cidr: "{{ cidr_vnet }}"

- name: Create subnet
  azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet_name }}"
      address_prefix_cidr: "{{ cidr_net }}"
      #virtual_network_name: "{{ name }}{{ rpfx }}"
      virtual_network_name: "{{ vnet_name }}"
  register: subnet