# Gather information about any VPC with a tag key Name and value Example
- amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ vpc_name }}"

- name: Create subnet 1 in VPC
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: 10.10.0.0/24
    map_public: no
    region: us-east-1
    tags:
      Name: "{{ vpc_name }}-subnet-1"