- hosts: localhost
  gather_facts: no
  tasks:
      - include_role:
           name: res_group
        vars:
           name: akscluster
           resource_group: Santander

- hosts: localhost
  gather_facts: no
  tasks:
      - include_role:
           name: aks
        vars:
           name: akscluster
           resource_group: Santander

- hosts: localhost
  gather_facts: no
  tasks:
      - include_role:
           name: argo

# - hosts: '{{ server }}'
#   gather_facts: no
#   any_errors_fatal: yes
#   roles: 
#     - weblogic-domain

# - hosts: '{{ server }}'
#   gather_facts: no
#   any_errors_fatal: yes
#   serial: 1
#   roles:
#     - weblogic-enroll

# - hosts: '{{ server }}'
#   gather_facts: no
#   any_errors_fatal: yes
#   tasks:
#     - import_role: 
#         name: weblogic-domain-servers
#         allow_duplicates: false

# - hosts: '{{ server }}'
#   gather_facts: no
#   roles: 
#     - icbs-domain-environment

# - hosts: '{{ server }}'
#   gather_facts: no
#   roles: 
#     - role: post-commons
#       vars:
#         ansible_user: root