---
- name: Eliminar recursos de AWS
  hosts: localhost
  tasks:
    - name: Incluir variables
      include_vars: defaults/main.yml

    - name: Eliminar nodos
      command:
        cmd: aws eks delete-nodegroup --cluster-name "{{ cluster_name }}" --nodegroup-name "{{ node_group }}"
      delegate_to: localhost

    - name: Esperar a que el nodegroup sea eliminado
      command:
        cmd: aws eks describe-nodegroup --cluster-name "{{ cluster_name }}" --nodegroup-name "{{ node_group }}"
      register: nodegroup_status
      until: "'DOES_NOT_EXIST' in nodegroup_status.stderr"
      retries: 10
      delay: 60
      delegate_to: localhost

    - name: Eliminar el clúster de EKS
      command:
        cmd: aws eks delete-cluster --name "{{ cluster_name }}"
      delegate_to: localhost

    - name: Get VPC ID by Name
      command:
        cmd: aws ec2 describe-vpcs --filters "Name=tag:Name,Values={{ vpc_name }}" --query "Vpcs[0].VpcId" --output text
      register: vpc_id_result
      delegate_to: localhost

    - set_fact:
        vpc_id: "{{ vpc_id_result.stdout }}"

    - name: Eliminar la VPC
      command:
        cmd: "aws ec2 delete-vpc --vpc-id {{ vpc_id }}"
      delegate_to: localhost