---
- name: Crear Application de ArgoCD en Kubernetes
  kubernetes.core.k8s:
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: configuraciones
        namespace: argocd
      spec:
        project: default
        source:
          repoURL: git@git.solem.cl:infra/argocd.git
          targetRevision: HEAD
          path: dss/dss-base
        destination:
          server: https://kubernetes.default.svc
          namespace: dss
        syncPolicy:
          syncOptions:
            - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true