# - name: Get EKS cluster info
#   community.aws.eks_cluster_info:
#     name: "{{ cluster_name }}"
#     region: "{{ region }}"
#   register: eks_info

- name: Get EKS cluster info
  ansible.builtin.command: 
    cmd: aws eks describe-cluster --name "{{ cluster_name }}" --region "{{ region }}"
  register: eks_info
  delegate_to: localhost

- name: Parse EKS cluster info
  set_fact:
    eks_info: "{{ eks_info.stdout | from_json }}"

# - name: Create kubeconfig
#   copy:
#     dest: "~/.kube/config"
#     content: |
#       apiVersion: v1
#       kind: Config
#       clusters:
#       - cluster:
#           server: "{{ eks_info.clusters[0].cluster.endpoint }}"
#           certificate-authority-data: "{{ eks_info.clusters[0].cluster.certificateAuthority.data }}"
#         name: "{{ cluster_name }}"
#       contexts:
#       - context:
#           cluster: "{{ cluster_name }}"
#           user: "{{ cluster_name }}"
#         name: "{{ cluster_name }}"
#       current-context: "{{ cluster_name }}"
#       users:
#       - name: "{{ cluster_name }}"
#         user:
#           exec:
#             apiVersion: client.authentication.k8s.io/v1alpha1
#             command: aws
#             args:
#             - "eks"
#             - "get-token"
#             - "--region"
#             - "{{ region }}"
#             - "--cluster-name"
#             - "{{ cluster_name }}"

- name: Create kubeconfig
  copy:
    dest: "~/.kube/config"
    content: |
      apiVersion: v1
      kind: Config
      clusters:
      - cluster:
          server: "{{ eks_info.cluster.endpoint }}"
          certificate-authority-data: "{{ eks_info.cluster.certificateAuthority.data }}"
        name: "{{ cluster_name }}"
      contexts:
      - context:
          cluster: "{{ cluster_name }}"
          user: "{{ cluster_name }}"
        name: "{{ cluster_name }}"
      current-context: "{{ cluster_name }}"
      users:
      - name: "{{ cluster_name }}"
        user:
          exec:
            apiVersion: client.authentication.k8s.io/v1alpha1
            command: aws
            args:
            - "eks"
            - "get-token"
            - "--region"
            - "{{ region }}"
            - "--cluster-name"
            - "{{ cluster_name }}"