---
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present

- name: Descargar Manifest ArgoCD
  get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    dest: /tmp/argocd-install.yaml

- name: Instalar Argo CD
  k8s:
    namespace: argocd
    state: present
    src: /tmp/argocd-install.yaml
- name: Cambiar el Servicio argocd-server a LoadBalancer
  community.kubernetes.k8s:
    kubeconfig: "~/.kube/config"
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: argocd-server
        namespace: argocd
      spec:
        type: NodePort

- name: Get the current ArgoCD admin password
  shell: "kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath=\"{.data.password}\" | base64 -d"
  register: Oldpassword

# - name: Obtener EL DNSName del Balancerador de carga
#   ansible.builtin.command: aws elb describe-load-balancers --query "LoadBalancerDescriptions[].DNSName" --output text
#   register: dnsname

- name: Get Load Balancer URL
  hosts: localhost  # Puedes ajustar esto según tu configuración
  tasks:
    - name: Get Load Balancer facts
      ec2_elb_facts:
        region: us-east-1  # Ajusta la región según tu configuración
      register: elb_facts

    - name: Set Load Balancer URL variable
      set_fact:
        load_balancer_url: "{{ elb_facts.elbs[0].dns_name }}"

- name: Change the ArgoCD admin password
  community.general.argocd_user:
    server: "https://{{ load_balancer_url }}"
    username: admin
    password: "{{ old_password.stdout }}"
    new_password: "Passw0rd"
    validate_certs: no  # Puedes cambiar esto a 'yes' si los certificados son válidos y configurados correctamente
  register: argocd_password_change_result

- name: Display result
  debug:
    var: argocd_password_change_result

- name: Change ArgoCD admin password using shell
  ansible.builtin.shell: "argocd account update-password --current-password OldPassw0rd --new-password Passw0rd"
  delegate_to: localhost

# - name: Change the ArgoCD admin password
#   shell: "argocd account update-password --current-password {{ old_password.stdout }} --new-password Passw0rd"

- name: Asegurarse de que el directorio /tmp/ginko no existe
  file:
    path: /tmp/ginko
    state: absent

- name: Clonar repositorio desde AWS CodeCommit usando SSH
  git:
    repo: 'ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/ginko'
    dest: '/tmp/santander'
    version: master
    key_file: '~/.ssh/id_rsa'
  environment:
    AWS_DEFAULT_REGION: 'us-east-1'

- name: Aplicar dss-application.yaml con kubectl
  command:
    cmd: kubectl apply -f /tmp/santander/dss-application.yaml
  delegate_to: localhost