---
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present

- name: Descargar Manifest ArgoCD
  get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    dest: /tmp/argocd-install.yaml

- name: Instalar Argo CD
  k8s:
    namespace: argocd
    state: present
    src: /tmp/argocd-install.yaml
- name: Cambiar el Servicio argocd-server a LoadBalancer
  community.kubernetes.k8s:
    kubeconfig: "~/.kube/config"
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: argocd-server
        namespace: argocd
      spec:
        type: LoadBalancer

- name: Get the current ArgoCD admin password
  shell: "kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath=\"{.data.password}\" | base64 -d"
  register: old_password

# - name: Change the ArgoCD admin password
#   shell: "argocd account update-password --current-password {{ old_password.stdout }} --new-password Passw0rd"

# - name: Clonar el repositorio de Git
#   git:
#     repo: 'https://git.solem.cl/infra/argocd'  # URL del repositorio
#     dest: '/tmp'

# - name: Clonar el repositorio de Git
#   git:
#     repo: 'git@git.solem.cl:infra/argocd.git'
#     dest: '/tmp'
#     version: 'master'
#     accept_hostkey: yes
#     depth: 1
#   environment:
#     GIT_ASKPASS: "/bin/echo"
#     GIT_USERNAME: "ivan.uribe"
#     GIT_PASSWORD: "glpat-SYs7vCNWR221r_7uVRUP"

- name: Clonar repositorio desde AWS CodeCommit usando SSH
  git:
    repo: 'ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/ginko'
    dest: '/tmp'
    version: master
    key_file: '~/.ssh/id_rsa'
  environment:
    AWS_DEFAULT_REGION: 'us-east-1'


- name: Aplicar dss-application.yaml con kubectl
  command:
    cmd: kubectl apply -f /tmp/argocd/dss-application.yaml
  delegate_to: localhost  # Ejecuta el comando en la máquina local