---
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present

- name: Descargar Manifest ArgoCD
  get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    dest: /tmp/argocd-install.yaml

- name: Instalar Argo CD
  k8s:
    namespace: argocd
    state: present
    src: /tmp/argocd-install.yaml
- name: Cambiar el Servicio argocd-server a LoadBalancer
  community.kubernetes.k8s:
    kubeconfig: "~/.kube/config"
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: argocd-server
        namespace: argocd
      spec:
        type: NodePort

- name: Get the current ArgoCD admin password
  shell: "kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath=\"{.data.password}\" | base64 -d"
  register: Oldpassword

- name: Change ArgoCD admin password via SSH
  hosts: localhost
  tasks:
    - name: Set up SSH port forwarding
      ansible.builtin.local_action:
        module: command
        cmd: "ssh -L 8080:localhost:8080 -L 443:localhost:443 admin@argo-server"
        executable: /bin/bash
      become: no
      async: 0
      poll: 0
      delegate_to: localhost

- name: Change ArgoCD admin password using shell
  ansible.builtin.shell: "argocd account update-password --current-password OldPassw0rd --new-password P@ssw0rd"
  delegate_to: localhost

# - name: Change the ArgoCD admin password
#   shell: "argocd account update-password --current-password {{ old_password.stdout }} --new-password Passw0rd"

- name: Asegurarse de que el directorio /tmp/ginko no existe
  file:
    path: /tmp/ginko
    state: absent

- name: Clonar repositorio desde AWS CodeCommit usando SSH
  git:
    repo: 'ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/ginko'
    dest: '/tmp/santander'
    version: master
    key_file: '~/.ssh/id_rsa'
  environment:
    AWS_DEFAULT_REGION: 'us-east-1'

- name: Aplicar dss-application.yaml con kubectl
  command:
    cmd: kubectl apply -f /tmp/santander/dss-application.yaml
  delegate_to: localhost