# - include_tasks: facts/main.yml
#   when: aks_facts.aks | length == 1
#   vars:
#     aks: "{{ aks_facts.aks[0] }}"

# create or update AKS
- name: Create or update AKS state
  azure_rm_aks:
      name: "{{ cluster_name }}"
      resource_group: "{{ resource_group }}"
      location: "{{ location }}"
      dns_prefix: "{{ dns_prefix }}"
      kubernetes_version: "{{ kubernetes_version }}"
      #enable_rbac: "{{ enable_rbac }}"
      #service_principal: "{{ sp | default(omit) }}"
      # linux_profile:
      #     admin_username: "{{ admin_username }}"
      #     ssh_key: "{{ ssh_key }}"
      #agent_pool_profiles: "{{ [agent_pool] | default(omit) }}"
      agent_pool_profiles:
          - name: system
            count: 1
            vm_size: Standard_D2_v2
            mode: System  # Definir el tipo como "System" para el grupo de agentes de sistema
          - name: default
            count: 2
            vm_size: Standard_D2_v2
      #network_profile: "{{ network_profile | default(omit) }}"
      #aad_profile: "{{ aad_profile | default(omit) }}"
      #addon: "{{ addon | default(omit) }}"
#   check_mode: yes
  register: aks