- name: Create CoreDNS addon
  ansible.builtin.command:
    cmd: aws eks create-addon --cluster-name "{{ cluster_name }}" --addon-name coredns --addon-version v1.10.1-eksbuild.1
  delegate_to: localhost
  ignore_errors: true

- name: Create kube-proxy addon
  ansible.builtin.command:
    cmd: aws eks create-addon --cluster-name "{{ cluster_name }}" --addon-name kube-proxy --addon-version v1.27.1-eksbuild.1
  delegate_to: localhost
  ignore_errors: true

- name: Create VPC CNI addon
  ansible.builtin.command:
    cmd: aws eks create-addon --cluster-name "{{ cluster_name }}" --addon-name vpc-cni --addon-version v1.12.6-eksbuild.2
  delegate_to: localhost
  ignore_errors: true