- name: Install CoreDNS
  community.kubernetes.k8s:
    state: present
    kubeconfig: /home/osboxes/.kube/config
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: coredns
        namespace: kube-system
      spec:
        ...
  register: coredns

- name: Install kube-proxy
  community.kubernetes.k8s:
    state: present
    kubeconfig: /home/osboxes/.kube/config
    definition:
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: kube-proxy
        namespace: kube-system
      spec:
        ...
  register: kube_proxy

- name: Install Amazon VPC CNI
  community.kubernetes.k8s:
    state: present
    kubeconfig: /home/osboxes/.kube/config
    definition:
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: aws-node
        namespace: kube-system
      spec:
        ...
  register: aws_cni