---
- name: Create an EKS cluster
  community.aws.eks_cluster:
    name: "{{ cluster_name }}"
    version: "{{ kubernetes_version }}"
    role_arn: "arn:aws:iam::348691576534:role/EKS_Cluster"
    subnets:
      - ["{{ public_subnet2.subnet.id }}", "{{ public_subnet3.subnet.id }}", "{{ public_subnet4.subnet.id }}"]
    security_groups:
      - "{{ sg_public }}"
    region: "{{ region }}"
  register: control_plane