---
- name: Create an EKS cluster
  community.aws.eks_cluster:
    name: "{{ cluster_name }}"
    version: "{{ kubernetes_version }}"
    role_arn: "arn:aws:iam::348691576534:role/EKS_Cluster"
    subnets:
      - "{{ public_subnet2.subnet.id }}"
      - "{{ public_subnet3.subnet.id }}"
      - "{{ public_subnet4.subnet.id }}"
    security_groups:
      - "{{ sg_public.group_id }}"
    region: "{{ region }}"
  register: control_plane

# - name: Update kubeconfig
#   ansible.builtin.command:
#     cmd: aws eks update-kubeconfig --name cluster-santander --region us-east-1
#   delegate_to: localhost
#   environment:
#     KUBECONFIG: /home/osboxes/.kube/config
#   become: yes
#   become_user: osboxes