---
- name: Create an EKS cluster
  community.aws.eks_cluster:
    name: "{{ cluster_name }}"
    version: "{{ kubernetes_version }}"
    role_arn: "arn:aws:iam::348691576534:role/EKS_Cluster"
    subnets:
      - "{{ public_subnet1.subnet.id }}"
      - "{{ public_subnet2.subnet.id }}"
      - "{{ public_subnet3.subnet.id }}"
    security_groups:
      - "{{ sg_public.group_id }}"
    region: "{{ region }}"
  register: control_plane

- name: Inform about cluster creation
  debug:
    msg: "Estado del cluster: Creando"
  delegate_to: localhost

- name: Check EKS cluster status
  ansible.builtin.command: >
    aws eks describe-cluster --name "{{ cluster_name }}" --query "cluster.status" --output text
  register: cluster_state
  until: cluster_state.stdout == 'ACTIVE'
  retries: 60
  delay: 30
  delegate_to: localhost

- name: Display final cluster status
  debug:
    msg: "Final cluster state: {{ cluster_state.stdout }}"
  delegate_to: localhost

# - name: Wait for EKS cluster to be active
#   ansible.builtin.command: >
#     aws eks describe-cluster --name "{{ cluster_name }}" --query "cluster.status" --output text
#   register: cluster_state
#   until: cluster_state.stdout == 'ACTIVE'
#   retries: 60
#   delay: 30
#   delegate_to: localhost

- name: Update kubeconfig
  ansible.builtin.command:
    cmd: aws eks update-kubeconfig --name "{{ cluster_name }}" --region us-east-1
  delegate_to: localhost
  environment:
    KUBECONFIG: ~/.kube/config
  become: true
  #become_user: osboxesroot

- name: Adding addons
  import_tasks: addons.yml
- name: Adding nodes
  import_tasks: nodes.yml